DEFAULT_NAME = "FlightRadar24"
DOMAIN = "flightradar24"
URL = 'https://www.flightradar24.com/'

CONF_MIN_ALTITUDE = "min_altitude"
CONF_MAX_ALTITUDE = "max_altitude"
CONF_MOST_TRACKED = "most_tracked"
CONF_ENABLE_TRACKER = "enable_tracker"
CONF_AUTO_CLEANUP = "auto_cleanup"
CONF_MOST_TRACKED_DEFAULT = True
CONF_ENABLE_TRACKER_DEFAULT = False
CONF_AUTO_CLEANUP_DEFAULT = False

CONF_TRACKER_NAME_STYLE = "tracker_name_style"
TRACKER_NAME_CALLSIGN = "callsign"
TRACKER_NAME_CALLSIGN_ROUTE = "callsign_route"
TRACKER_NAME_REG_ROUTE = "reg_route"
CONF_TRACKER_NAME_DEFAULT = TRACKER_NAME_CALLSIGN

TRACKER_NAME_OPTIONS = [
    TRACKER_NAME_CALLSIGN,
    TRACKER_NAME_CALLSIGN_ROUTE,
    TRACKER_NAME_REG_ROUTE,
]

EVENT_ENTRY = f"{DOMAIN}_entry"
EVENT_EXIT = f"{DOMAIN}_exit"
EVENT_AREA_LANDED = f"{DOMAIN}_area_landed"
EVENT_AREA_TOOK_OFF = f"{DOMAIN}_area_took_off"
EVENT_TRACKED_LANDED = f"{DOMAIN}_tracked_landed"
EVENT_TRACKED_TOOK_OFF = f"{DOMAIN}_tracked_took_off"
EVENT_MOST_TRACKED_NEW = f"{DOMAIN}_most_tracked_new"

MIN_ALTITUDE = -1
MAX_ALTITUDE = 100000
