
---
name: Validate HACS
on:
  push:
  pull_request:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Download repo
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        name: Setup Python
        with:
          python-version: '3.10.x'

      - uses: actions/cache@v4
        name: Cache
        with:
          path: |
            ~/.cache/pip
          key: custom-component-ci

      - name: HACS Action
        uses: hacs/action@main
        with:
          CATEGORY: integration
