
---
name: Validate with hassfest

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
        name: Download repo
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        name: Setup Python
        with:
          python-version: '3.10.x'
      - uses: "actions/checkout@v4"
      - uses: home-assistant/actions/hassfest@master
